MyFabricStashApp/Models/Receipt.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyFabricStashApp.Models
{
    public class Receipt
    {
        public int ReceiptId { get; set; }
        public string ReceiptImagePath { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}",ApplyFormatInEditMode = true)]
        public DateTime ReceiptDate { get; set; }
        public string Description { get; set; }

    }
}

MyFabricStashApp/Controllers/ReceiptsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyFabricStashApp.Models;
using System.IO;

namespace MyFabricStashApp.Controllers
{
    public class ReceiptsController : Controller
    {
        private MyFabricStashDb db = new MyFabricStashDb();

        // GET: Receipts
        public ActionResult Index()
        {
            var orderedList = db.Receipts.Include(s => s.Source)
                .OrderByDescending(d => d.ReceiptDate)
                .Select(r => new ReceiptsListViewModel
                {
                    ReceiptId = r.ReceiptId,
                    ReceiptNumber = r.ReceiptNumber,
                    SourceId = r.SourceId,
                    SourceName = r.Source.SourceName,
                    ReceiptImagePath = r.ReceiptImagePath,
                    ReceiptDate = r.ReceiptDate,
                    Description = r.Description
                });
            return View(orderedList);
        }

        // GET: Receipts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receipt receipt = db.Receipts.Find(id);
            if (receipt == null)
            {
                return HttpNotFound();
            }
            return View(receipt);
        }

        // GET: Receipts/Create
        public ActionResult Create()
        {
            List<Source> lstSources = db.Sources.ToList();

            lstSources.Insert(0, new Source { SourceId = 0, SourceName = "--Select Source--" });

            ViewBag.SourceId = new SelectList(lstSources, "SourceId", "SourceName");

            return View();
        }

        // POST: Receipts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReceiptId,ReceiptImagePath,SourceId,ReceiptDate,Description")] Receipt receipt, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var filename = Path.GetFileName(file.FileName);
                    string receiptId = receipt.ReceiptId.ToString();
                    string myfile = receiptId + "_" + filename;
                    var path = Path.Combine(Server.MapPath("~/receipts"), myfile);
                    receipt.ReceiptImagePath = myfile;
                    file.SaveAs(path);
                }
                
                db.Receipts.Add(receipt);
                db.SaveChanges();
                receipt.ReceiptNumber = "REC0" + receipt.ReceiptId.ToString() + receipt.ReceiptDate.ToString("yyyyMMdd") + receipt.SourceId;
                db.Entry(receipt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(receipt);
        }

        // GET: Receipts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receipt receipt = db.Receipts.Find(id);
            if (receipt == null)
            {
                return HttpNotFound();
            }
            return View(receipt);
        }

        // POST: Receipts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReceiptId,ReceiptImagePath,ReceiptDate,Description")] Receipt receipt)
        {
            if (ModelState.IsValid)
            {
                db.Entry(receipt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(receipt);
        }

        // GET: Receipts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receipt receipt = db.Receipts.Find(id);
            if (receipt == null)
            {
                return HttpNotFound();
            }
            return View(receipt);
        }

        // POST: Receipts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Receipt receipt = db.Receipts.Find(id);
            db.Receipts.Remove(receipt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyFabricStashApp/Views/Receipts/Create.cshtml
@model MyFabricStashApp.Models.Receipt

@{
    ViewBag.Title = "Create";
}
<script type="text/javascript">
    $(function () {
        $('.date-picker').datepicker();
    })
</script>
@*@Html.Partial("~/Views/Shared/_DatePicker.cshtml")*@

<h2>Add New Receipt</h2>


@using (Html.BeginForm("Create", "Receipts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Receipt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class = "control-label col-md-2">Receipt Image</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ReceiptImagePath, new { htmlAttributes = new { @class = "form-control" } })*@
                <div>
                    <img id="user_img" width="150" />
                </div>
                <br />
                <input type="file" title="Upload Image" id="file" name="file" onchange="show(this)" />
                @Html.ValidationMessageFor(model => model.ReceiptImagePath, "", new { @class = "text-danger" })
                <script type="text/javascript">
                    function show(input) {
                        if (input.files && input.files[0]) {
                            var filereader = new FileReader();
                            filereader.onload = function (e) {
                                $('#user_img').attr('src', e.target.result);
                            }
                            filereader.readAsDataURL(input.files[0]);
                        }
                    }
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Receipt Date</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReceiptDate, new { htmlAttributes = new { @class = "form-control date-picker" } })
                @Html.ValidationMessageFor(model => model.ReceiptDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyFabricStashApp/Views/Receipts/Delete.cshtml
@model MyFabricStashApp.Models.Receipt

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Receipt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Receipt Image
        </dt>

        <dd>
            <img src='~/receipts/@Model.ReceiptImagePath' width="300" />
        </dd>

        <dt>
            Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiptDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyFabricStashApp/Views/Receipts/Details.cshtml
@model MyFabricStashApp.Models.Receipt

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Receipt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReceiptImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiptImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiptDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiptDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ReceiptId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyFabricStashApp/Views/Receipts/Edit.cshtml
@model MyFabricStashApp.Models.Receipt

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Receipt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ReceiptId)

        <div class="form-group">
            @Html.LabelFor(model => model.ReceiptImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReceiptImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReceiptImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReceiptDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReceiptDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReceiptDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyFabricStashApp/Views/Receipts/Index.cshtml
@model IEnumerable<MyFabricStashApp.Models.ReceiptsListViewModel>

@{
    ViewBag.Title = "Receipts List";
}

<h2>Receipts List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Receipt Image
        </th>
        <th>
            Receipt Number
        </th>
        <th>
            Date
        </th>
        <th>
            Source
        </th>
        <th>
            Description
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src='~/receipts/@item.ReceiptImagePath' width="150" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReceiptNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReceiptDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SourceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ReceiptId }) |
            @Html.ActionLink("Details", "Details", new { id = item.ReceiptId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ReceiptId })
        </td>
    </tr>
}

</table>